config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: :logout

  resources :events
  resources :retirements
  resources :events do
    resources :tickets
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :tickets, dependent: :destroy

  belongs_to :owner, class_name: 'User'

  validates :name, length: { maximum: 50 }, presence: true
  validates :place, length: { maximum: 50 }, presence: true
  validates :content, length: { maximum: 2000 }, presence: true
  validates :start_at, presence: true
  validates :end_at, presence: true
  validate :start_at_should_be_before_end_at

  def created_by?(user)
    return false unless user
    owner_id == user.id
  end

  private

  def start_at_should_be_before_end_at
    return unless start_at && end_at

    if start_at >= end_at
      errors.add(:start_at, 'は終了時間よりも前に設定してください')
    end
  end
end

app/models/freee/authentication.rb
module Freee
  class Authentication
  end
end

app/models/output_sheet/base.rb
module OutputSheet
  class Base
  end
end

app/models/output_sheet/users.rb
module OutputSheet
  class Users
    self.class.name
  end
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user, optional: true # nilを許可する
  belongs_to :event

  validates :comment, length: { maximum: 30 }, allow_blank: true
end

app/models/user.rb
class User < ApplicationRecord
  before_destroy :check_all_events_finished

  has_many :created_events, class_name: 'Event', foreign_key: 'owner_id', dependent: :nullify
  has_many :tickets, dependent: :nullify
  has_many :participating_events, through: :tickets, source: :event

  def self.find_or_create_from_auth_hash!(auth_hash)
    provider = auth_hash[:provider]
    uid = auth_hash[:uid]
    nickname = auth_hash[:info][:nickname]
    image_url = auth_hash[:info][:image]

    User.find_or_create_by!(provider: provider, uid: uid) do |user|
      user.name = nickname
      user.image_url = image_url
    end
  end

  private

  def check_all_events_finished
    now = Time.zone.now
    if created_events.where(":now < end_at", now: now).exists?
      errors[:base] << '公開中の未終了イベントが存在します'
    end

    if participating_events.where(':now < end_at', now: now).exists?
      errors[:base] << '未終了の参加イベントが存在します'
    end

    throw(:abort) unless errors.empty?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate
  helper_method :logged_in?, :current_user

  private

  def logged_in?
    !!session[:user_id]
  end

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
  end

  def authenticate
    return if logged_in?
    redirect_to root_path, alert: 'ログインしてください'
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authenticate, only: :show

  def new
    @event = current_user.created_events.build
  end

  def create
    @event = current_user.created_events.build(event_params)

    if @event.save
      redirect_to @event, notice: '作成しました'
    end
  end

  def show
    @event = Event.find(params[:id])
    @ticket = current_user && current_user.tickets.find_by(event: @event)
    @tickets = @event.tickets.includes(:user).order(:created_at)
  end

  def edit
    @event = current_user.created_events.find(params[:id])
  end

  def update
    @event = current_user.created_events.find(params[:id])
    if @event.update(event_params)
      redirect_to @event, notice: '更新しました'
    end
  end

  def destroy
    @event = current_user.created_events.find(params[:id])
    @event.destroy!
    redirect_to root_path, notice: '削除しました'
  end

  private

  def event_params
    params.require(:event).permit(:name, :place, :content, :start_at, :end_at)
  end
end

app/controllers/retirements_controller.rb
class RetirementsController < ApplicationController
  def new
  end

  def create
    if current_user.destroy
      reset_session
      redirect_to root_path, notice: '退会完了しました'
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate, only: :create

  def create
    user = User.find_or_create_from_auth_hash!(request.env['omniauth.auth'])
    session[:user_id] = user.id
    redirect_to root_path, notice: 'ログインしました'
  end

  def destroy
    reset_session
    redirect_to root_path, notice: 'ログアウトしました'
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def new
    raise ActionController::RoutingError, 'ログイン状態でTicketsController#newにアクセス'
  end

  def create
    event = Event.find(params[:event_id])
    @ticket = current_user.tickets.build do |t|
      t.event = event
      t.comment = params[:ticket][:comment]
    end
    if @ticket.save
      redirect_to event, notice: 'このイベントに参加表明しました'
    end
  end

  def destroy
    ticket = current_user.tickets.find_by!(event_id: params[:event_id])
    ticket.destroy!
    redirect_to event_path(params[:event_id]), notice: 'このイベントの参加をキャンセルしました'
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def output_sheet
    @users = User.all
    workbook = RubyXL::Parser.parse("excel_templates/users.xlsx")
    workbook[0].sheet_name = 'ユーザー一覧'
    # worksheet1 = workbook[0]
    # row1 = worksheet1[0]
    # cell1 = row1[0]

    send_data workbook, type: workbook.content_type
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :age, :address)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate

  def index
    @events = Event.where("start_at > ?", Time.zone.now).order(:start_at)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def url_for_github(user)
    "https://github.com/#{ user.name }"
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/retirements_helper.rb
module RetirementsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/application/_errors.html.slim
.alert.alert-danger
  ul.mb-0
    - errors.full_messages.each do |message|
      li = message

app/views/events/create.js.erb
document.getElementById('errors').innerHTML = "<%=j render("errors", errors: @event.errors) %>"

app/views/events/edit.html.slim
- now = Time.zone.now

h1.mt-2 = t('.page_title')

= form_with(model: @event, class: 'form-horizontal') do |f|
  #errors

  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'

  .form-group
    = f.label :place
    = f.text_field :place, class: 'form-control'

  .form-group
    = f.label :start_at
    div
      = f.datetime_select :start_at, start_year: now.year, end_year: now.year + 1

  .form-group
    = f.label :end_at
    div
      = f.datetime_select :end_at, start_year: now.year, end_year: now.year + 1

  .form-group
    = f.label :content
    = f.text_area :content, class: 'form-control', row: 10

  = f.submit class: 'btn btn-primary'

app/views/events/new.html.slim
- now = Time.zone.now

h1.mt-2 イベント作成

= form_with(model: @event, class: 'form-horizontal') do |f|
  #errors

  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'

  .form-group
    = f.label :place
    = f.text_field :place, class: 'form-control'

  .form-group
    = f.label :start_at
    div
      = f.datetime_select :start_at, start_year: now.year, end_year: now.year + 1

  .form-group
    = f.label :end_at
    div
      = f.datetime_select :end_at, start_year: now.year, end_year: now.year + 1

  .form-group
    = f.label :content
    = f.text_area :content, class: 'form-control', row: 10

  = f.submit class: 'btn btn-primary'

app/views/events/show.html.slim
h1.mt-3.mb-3 = @event.name

.row
  .col-8
    .card.mb-2
      h5.card-header = t('.content')
      .card-body
        p.card-text = @event.content

    .card.mb-2
      h5.card-header = t('.held_at')
      .card-body
        p.card-text = "#{ l(@event.start_at, format: :long) } - #{ l(@event.end_at, format: :long) }"

    .card.mb-2
      h5.card-header = t('.place')
      .card-body
        p.card-text = @event.place

    .card.mb-2
      h5.card-header = t('.owner')
      .card-body
        - if @event.owner
          = link_to("https://github.com/#{ @event.owner.name }", class: 'card-link') do
            = image_tag @event.owner.image_url, width: 50, height: 50
            = "@#{ @event.owner.name }"
        - else
          | 退会したユーザーです
  .col-4
    - if @event.created_by?(current_user)
      = link_to 'イベントを編集する', edit_event_path(@event), class: 'btn btn-info btn-lg btn-block'
      = link_to 'イベントを削除する', event_path(@event), class: 'btn btn-danger btn-lg btn-block', method: :delete, data: { confirm: '本当に削除しますか？' }

    - if @ticket
      = link_to '参加をキャンセルする', event_ticket_path(@event, @ticket), method: :delete, class: 'btn btn-warning btn-lg btn-block'
    - elsif logged_in?
      button.btn.btn-primary.btn-lg.btn-block data-toggle='modal' data-target='#createTicket'
        | 参加する
      .modal.fade#createTicket
        .modal-dialog
          .modal-content
            .modal-header
              h4.modal-title#dialogHeader 参加コメント
              button.close type='button' data-dismiss='modal' &times;

            = form_with(model: @event.tickets.build, url: event_tickets_path(@event)) do |f|
              .modal-body
                #createTicketErrors
                = f.text_field :comment, class: 'form-control'
              .modal-footer
                button.btn.btn-default type='button' data-dismiss='modal'
                  | キャンセル
                = f.button '送信', class: 'btn btn-primary'
    - else
      = link_to '参加する', new_event_ticket_path(@event), class: 'btn btn-primary btn-lg btn-block'

    hr
      .card.mb-2
        h5.card-header 参加者
        ul.list-group.list-group-flush
          - @tickets.each do |ticket|
            li.list-group-item
              - if ticket.user
                = link_to(url_for_github(ticket.user), class: 'card-link') do
                  = image_tag ticket.user.image_url, width: 20, height: 20
                  = "@#{ ticket.user.name }"
                = ticket.comment
              - else
                | 退会したユーザーです

app/views/events/update.js.erb
document.getElementById("errors").innerHTML = "<%=j render('errors', errors: @event.errors) %>"

app/views/retirements/create.js.erb
document.getElementById('errors').innerHTML = "<%=j render("errors", errors: current_user.errors) %>"

app/views/retirements/new.html.slim
h1.mt-3 退会の確認

#errors

p 退会した場合、ユーザーに関するデータが全て削除されます。
p ただし、以下の場合は退会できません。

ul
  li
    公開中の未終了イベントがある場合
  li
    未終了の参加イベントがある場合
hr

= link_to '退会する', retirements_path, method: :post, remote: true, class: 'btn btn-danger', data: { confirm: '本当に退会しますか？' }

app/views/tickets/create.js.erb
document.getElementById('createTicketErrors').innerHTML = "<%=j render("errors", errors: @ticket.errors) %>"

app/views/users/_form.html.slim
= form_with(model: user, local: true) do |form|
  - if user.errors.any?
    #error_explanation
      h2
        = pluralize(user.errors.count, "error")
        |  prohibited this user from being saved:
      ul
        - user.errors.full_messages.each do |message|
          li
            = message
  .field
    = form.label :name
    = form.text_field :name
  .field
    = form.label :email
    = form.text_field :email
  .field
    = form.label :age
    = form.number_field :age
  .field
    = form.label :address
    = form.text_field :address
  .actions
    = form.submit

app/views/users/edit.html.slim
h1
  | Editing User
= render 'form', user: @user
= link_to 'Show', @user
|  | 
= link_to 'Back', users_path

app/views/users/index.html.slim
.users
  p#notice
    = notice
  h1
    | Users
  table
    thead
      tr
        th
          | Name
        th
          | Email
        th
          | Age
        th
          | Address
        th[colspan="3"]
    tbody
      - @users.each do |user|
        tr
          td
            = user.name
          td
            = user.email
          td
            = user.age
          td
            = user.address
          td
            = link_to 'Show', user
          td
            = link_to 'Edit', edit_user_path(user)
          td
            = link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }
  br
  = link_to 'New User', new_user_path

  = link_to '出力する', output_sheet_users_path(@users), class: 'mt8 button-success'

app/views/users/new.html.slim
h1
  | New User
= render 'form', user: @user
= link_to 'Back', users_path

app/views/users/show.html.slim
p#notice
  = notice
p
  strong
    | Name:
  = @user.name
p
  strong
    | Email:
  = @user.email
p
  strong
    | Age:
  = @user.age
p
  strong
    | Address:
  = @user.address
= link_to 'Edit', edit_user_path(@user)
|  | 
= link_to 'Back', users_path

app/views/welcome/index.html.slim
h1 = t('.events')

ul.list-group
  - @events.each do |event|
    = link_to(event, class: 'list-group-item list-group-item-action') do
      h5.list-group-item-heading = event.name
      p.mb-1 = "#{ l(event.start_at, format: :long) } - #{ l(event.end_at, format: :long) }"